[workspace]
resolver = "2"
members = ["apps/desktop/src-tauri", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/RightStackUK/open-note"
rust-version = "1.82"

[workspace.dependencies]
git-port = { path = "crates/git-port" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
